RedHatInsights/insights-api-common-rails

manageiq-api-common.gemspec
Each application that includes this should specify its specific version of rails if necessary.
=> Loosen dependency on rails

lib/manageiq/api/common/metrics.rb
This will make it easier to select metrics from different
services in prometheus after they are collected.
=> Add a prefix to the metrics collector

lib/manageiq/api/common/paginated_response.rb, spec/lib/manageiq/api/common/paginated_response_spec.rb
Limit:
- Less than 1 doesn't make sense
- More than 1000 (guess) may cause server problems (timeouts / lots of memory used)
Offset:
- Negative numbers don't make sense
=> Maximums and minimums for limit and offset

bin/console, lib/manageiq/api/common.rb, lib/manageiq/api/common/headers.rb, spec/lib/manageiq/api/common/headers_spec.rb
1. Sets / Get a thread safe version of any Rails header `ManageIQ::API::Common::Headers.current = headers` makes use of  `Thread.current[:attr_current_headers]`
2. Provides simple validation forcing a saved header using the Rails `ActionDispatch::Http::Headers` type.
Addresses this #29
=> Add common header utility

lib/manageiq/api/common/paginated_response.rb, spec/lib/manageiq/api/common/paginated_response_spec.rb
- Return relative links for pagination
- Only return link references that have values in order to be swagger compliant
=> Pagination fixes

lib/manageiq/api/common/paginated_response.rb, spec/lib/manageiq/api/common/paginated_response_spec.rb
It's convenient to have all the paging metainformation available in every paginated responses.
Adding the `limit` and `offset` fields.
Ping @Hyperkid123
=> Add limit and offset to PaginatedResponse meta.

lib/manageiq/api/common/user.rb, spec/lib/manageiq/api/common/user_spec.rb
@syncrou What do you think?
This trims up the repetition, makes find_user_key work on decode directly the same way find_tenant does, and changes the `?` accessors to not have the leading `is_`
=> Refactor user accessors

lib/manageiq/api/common/exceptions.rb, lib/manageiq/api/common/request.rb, lib/manageiq/api/common/user.rb, spec/lib/manageiq/api/common/request_spec.rb
Additionally add a helper method Request.current! that raises when then
Request.current is not set.
@syncrou Please review.  If there is any calling code actually catching HeadersNotSet, it would have to be changed for this PR.  If needed I can add a temporary alias of the constant.
cc @bdunne
=> Rename HeadersNotSet to RequestNotSet

lib/manageiq/api/common.rb, lib/manageiq/api/common/exceptions.rb, lib/manageiq/api/common/request.rb, lib/manageiq/api/common/user.rb, spec/lib/manageiq/api/common/request_spec.rb, spec/lib/manageiq/api/common/user_spec.rb
This PR adds accessors for specific header keys in the Request, and by doing so separates the "header" knowledge from the User class.  That is, the user just gets the identity hash from the request and doesn't have to know it's a header.
@syncrou Please review
Built on #43 so just review the second commit.
Closes #36
=> Add accessors for headers

lib/manageiq/api/common/request.rb, spec/lib/manageiq/api/common/request_spec.rb
We were incorrectly using x-request-id
The x-request-id comes from rails via this config setting
https://github.com/ManageIQ/catalog-api/blob/daa356d660efc78bcc5d5375a5917fbb463a3f0d/config/environments/production.rb#L48
=> Using the wrong header key for x-rh-insights-request-id

lib/manageiq/api/common/request.rb, spec/lib/manageiq/api/common/request_spec.rb
- Exposing optional_auth? and related required_auth?
- The common paths include:
- /api/.*/v#[.#]/openapi.json (osd deployment)
- /api/v#[.#]/openapi.json (rails dev env)
=> Added support in ManageIQ::API::Common::Request to know about request paths with optional authentication

lib/manageiq/api/common/request.rb, spec/lib/manageiq/api/common/request_spec.rb
Instead of letting the `KeyError` blow through here and subsequently rescuing for something as generic as KeyError, raise `ManageIQ::API::Common::IdentityError` instead since there isn't an identity to begin with due to the lack of an `x-rh-identity` header. 
On the catalog side we've been rescuing from a `KeyError` for a long time, but this makes much more sense and is more descriptive. It also allows us to change the rails behavior on `ActionController::ParameterMissing` since that is a KeyError itself it was hard to handle it any differently application-wide.
=> Raise IdentityError if x-rh-identity doesn't exist on User initialize

lib/manageiq/api/common/request.rb, spec/lib/manageiq/api/common/request_spec.rb
Fix an issue for
https://github.com/ManageIQ/manageiq-api-common/pull/55/files#diff-35dc214cbf96bc055529320b09ba5ee3R46 where we need to restore from saved current which is a type of `ManageIQ::API::Common::Request` if not `nil`, but the setter does not accept this type.
=> Allow .current= argument to be a ManageIQ::API::Common::Request type

spec/spec_helper.rb
When running tests locally for the common gem, the default warning doesn't reference the path
where the `database.yml` file is missing.
This error message loads from `spec_helper.rb` and stops the specs
unless the file exists. It also references where the `database.yml` file should be placed.
=> Print a warning when no spec dummy database.yml exists

lib/manageiq/api/common.rb, lib/manageiq/api/common/entitlement.rb, lib/manageiq/api/common/request.rb, spec/lib/manageiq/api/common/entitlements_spec.rb, spec/support/user_header_spec_helper.rb
Adds `Entitlement` class allowing services to query current enabled / disabled entitlements on a service.
This PR does _not_ raise the `EntitlementError` even though it is setup inline with the class. Until Entitlements are checked in all services, we are allowing all requests through if the `entitlements` key is not found.
```
"entitlements": {
"hybrid_cloud": {
"is_entitled": true
},
"insights": {
"is_entitled": true
},
"openshift": {
"is_entitled": true
},
"smart_management": {
"is_entitled": true
}
}
}
```
Examples:
```
2.4.1 :001 >  ent_hash =  {"entitlements" => {
2.4.1 :002 >           "hybrid_cloud" => {
2.4.1 :003 >               "is_entitled" => true
2.4.1 :004?>           },
2.4.1 :005 >           "insights" => {
2.4.1 :006 >               "is_entitled" => true
2.4.1 :007?> …
```
=> Add entitlements

lib/manageiq/api/common/request.rb, spec/lib/manageiq/api/common/request_spec.rb
Currently it validates the request to contain the header key
x-rh-insights-request-id if its missing it raises the KeyError
Suppressing it to return a nil if the key doesn't exist
=> If the x-rh-insights-request-id is missing return nil

lib/manageiq/api/common/open_api/docs/doc_v3.rb
Don't wrap the OpenApi Doc in a content key
Fixes https://github.com/ManageIQ/manageiq-api-common/issues/64
=> Return Api::Docs to not return content

lib/manageiq/api/common/logging.rb, manageiq-api-common.gemspec
Requires a new version of manageiq-loggers which includes https://github.com/ManageIQ/manageiq-loggers/pull/9
=> Use the cloud watch logger

lib/manageiq/api/common/graphql/generator.rb
- Do not advertise attributes which should not be fetched (e.g. encrypted password attributes) so exclude them from the auto-generated GraphQL schema since this is only used for query (No Mutation) for now.
=> Do not include Encrypted attributes in the GraphQL Schema

lib/manageiq/api/common/metrics.rb, lib/manageiq/api/common/middleware/web_server_metrics.rb, manageiq-api-common.gemspec
- Additional process metrics
- Add a counter for incoming requests (including exceptions)
- Add a histogram to track endpoint timings
- Add a gague to show the number of busy puma threads per server
=> Switch from PrometheusClient to PrometheusExporter

lib/manageiq/api/common/middleware/web_server_metrics.rb
When the Puma server is not initialized (doing anything other than rails s) the @get_stats variable on the Puma module is not defined, so calling stats on it raises NoMethodError.
=> Fix NoMethodError (undefined method `stats' for nil:NilClass)

lib/manageiq/api/common/graphql.rb
Improved the OpenAPI 3.0 post spec for the GraphQL endpoint.
- mentioning the required query parameter as well as the optional operationName and variables in the payload
- mentioning the data and errors properties in the response
=> Improved the OpenAPI 3.0 post spec for the GraphQL endpoint.

lib/manageiq/api/common/open_api/docs/component_collection.rb
Swagger doc Definition doesn't want '/' at the start/end of pattern.
https://swagger.io/docs/specification/data-models/data-types/#pattern
`OpenAPIParser` validates pattern and wraps pattern with '/', so this check is not compatible.
Wrong definition is for example there:
https://github.com/ManageIQ/sources-api/blob/master/public/doc/openapi-3-v1.0.0.json#L1200
check value against pattern here: https://github.com/ota42y/openapi_parser/blob/master/lib/openapi_parser/schema_validators/string_validator.rb#L50
Happened during implementation of https://github.com/ManageIQ/manageiq-api-common/issues/67
cc @bdunne @Ladas @abellotti
=> Removed OpenAPI Regexp validation

lib/manageiq/api/common/graphql/generator.rb
Fixed the schema generator so that it properly parses the subcollection name out of references as follows:
```
/primary_collection/{primary_collection_id}/subcollection/{id}
```
Used to only handle the following properly:
```
/primary_collection/{id}
```
=> Fixed the schema generator to properly parse subcollections

lib/manageiq/api/common/open_api/docs/doc_v3.rb, manageiq-api-common.gemspec
Adding `validate!` method to OpenAPI doc. It uses OpenAPIParser (https://github.com/ota42y/openapi_parser)
* Implements: #67
=> OpenAPIParser for requests validation

lib/manageiq/api/common/graphql/generator.rb, lib/manageiq/api/common/graphql/templates/query_type.erb, lib/manageiq/api/common/open_api/docs.rb, lib/manageiq/api/common/open_api/docs/component_collection.rb, lib/manageiq/api/common/open_api/docs/doc_v3.rb, lib/manageiq/api/common/open_api/serializer.rb
Occasionally we get an error about missing constant ManageIQ::Api::Docs
which should be actually be finding ::Api::Docs in lib/api/docs.rb in the
apps, but for some reason that isn't loaded yet.  Instead, move all of this
logic to manageiq-api-common and create
::ManageIQ::API::Common::OpenApi::Docs.instance
=> Fix constant problems

lib/manageiq/api/common/graphql.rb
- Moving the GraphQL Response into a separate schema definition as the client generator was getting confused with the inline response definition.
=> Splitting the GraphQL OpenAPI description

lib/manageiq/api/common/graphql.rb, lib/manageiq/api/common/graphql/associated_records.rb, lib/manageiq/api/common/graphql/association_loader.rb, lib/manageiq/api/common/graphql/generator.rb, lib/manageiq/api/common/graphql/templates/model_type.erb, lib/manageiq/api/common/graphql/templates/query_type.erb, lib/manageiq/api/common/paginated_response.rb, manageiq-api-common.gemspec
Drop support for the relay based specification and implements the base GraphQL query structure.
- Adding support for the following on collections:
- offset
- limit
- filter
- And the following on associations:
- offset
- limit
Example with topological inventory:
```
{
container_groups(filter: { name: { starts_with: "sources"}}) {
id
name
containers (offset: 90, limit: 30) {
id
name
archived_at
}
tags (offset: 20, limit: 20) {
id
description
}
}
}
```
Example with sources:
```
{
sources(offset: 10, limit: 10, filter: { name: "OpenShift"}) {
id
name
endpoints {
id
scheme
host
port
path
authentications {
id
username
status
}
}
}
}
```
=> Drop relay based spec for base GraphQL query structure with filter/offset/limit

lib/manageiq/api/common/graphql/generator.rb, lib/manageiq/api/common/graphql/templates/query_type.erb
Support for ClassName as well as ClassNameOut schema name definition in the OpenAPI spec.
This allows us support either the default ClassName or alternate ClassNameOut as used by the approval-api service. While a more elaborate implementation via the schema_overlay parameter can be done to allow for arbitrary name mappings, it seemed unnecessary for this one case (i.e. over engineered), we can revisit if another micro-service has a similar requirement but needing a different mapping.
=> Support Alternate OpenAPI Schema Class Name

lib/manageiq/api/common/graphql/generator.rb, lib/manageiq/api/common/graphql/templates/query_type.erb
Adding support for an optional base_query provided by the GraphQL controller for defining a base_query via the schema overlay for the different model queries.
Example would be something like:
```
schema_overlay = {
"^.*$" => {
"base_query" => ::Api::GraphqlController.method(:base_query)
}
}
graphql_api_schema = ::ManageIQ::API::Common::GraphQL::Generator.init_schema(request, schema_overlay)
```
Calls to ::Api::GraphqlController base_query would be as follows:
```
::Api::GraqhqlController.base_query(model_class, ctx)
```
Where ctx is the field resolver context.
=> Adding support for an optional base_query 

app/models/authentication.rb, spec/dummy/db/seeds.rb
update_attributes and update_attributes! are deprecated starting in Rails 6
See https://rubyinrails.com/2019/04/09/rails-6-1-activerecord-deprecates-update-attributes-methods/ for details and Rails PR links
@miq-bot add_label technical debt
=> update_attributes deprecation

lib/manageiq/api/common/application_controller_mixins/openapi_enabled.rb, lib/manageiq/api/common/application_controller_mixins/request_body_validation.rb, spec/dummy/app/controllers/application_controller.rb
Only openapi specific controllers should get validated with the
openapi json spec.
This uses a class variable at the controller level 
openapi_enabled
to check if we the class supports openapi validation.
For the classes that dont need openapi_validation the developer can set it to false.
=> Support for non openapi controllers

spec/requests/request_body_validation_spec.rb, spec/support/default_as_json.rb, spec/support/requests_spec_helper.rb
Opening this PR in favor of https://github.com/ManageIQ/catalog-api/pull/369, since it appears that more than just catalog will make use of this spec change.
=> Default to add ':as => :json' for all patch, post, and put request specs

spec/support/requests_spec_helper.rb
@bdunne After updating to the latest manageiq-api-common on catalog, specs were failing because the require for the `default_as_json` file was attempting to look in `spec/support` but since that file doesn't exist in the catalog project (or any other project that would use this), it was failing. This should fix that 😄 
/cc @syncrou
=> Fix require default_as_json to be relative

lib/manageiq/api/common/application_controller_mixins/request_path.rb, spec/lib/manageiq/api/common/application_controller_mixins/request_path_spec.rb
Previously it could be captured as part of the primary_collection_id and cause id validation to fail
=> Ignore the query string on id validation

lib/manageiq/api/common/graphql.rb
Without this, the GraphiQL app could not be used while enabling the validator on graphql requests.
With this, we don't need the 
```
skip_before_action :validate_request
```
in the GraphQL controllers.
=> Allow use of GraphiQL with enabling the openapi validator

lib/manageiq/api/common.rb, lib/manageiq/api/common/api_error.rb
This PR adds an exception class that wraps the `ErrorDocument` class so we can use it across catalog/approval so we can be in compliance with the IPP.
=> add api error class for use across microservices

lib/manageiq/api/common/graphql/generator.rb, spec/dummy/public/doc/openapi-3-v1.0.0.json
Enhanced the GraphQL schema generator to support other than the {id} references in the paths, namely {anything_id} with a more flexible {[[a-z]*_]*id} match
=> Enhanced GraphQL parsing of OpenAPI component paths

lib/manageiq/api/common/graphql.rb, lib/manageiq/api/common/open_api/generator.rb, spec/dummy/public/doc/openapi-3-v1.0.0.json
Updated the OpenAPI auto-generation and docs have the GraphQL declared via a separate schema entry.
=> Updated the OpenAPI to declare the GraphQL request as a separate entry

lib/manageiq/api/common/graphql/generator.rb
Fixes warning when GraphQL schema generator tries to redefined  model type already defined.
Fixes #111 
/cc @mkanoor
=> Fixes warning with GraphQL schema generator

lib/manageiq/api/common/request.rb
A logged in user may have multiple roles, there is need to get resources based on a selected role (persona) instead of all roles. A customized header `x-rh-persona` is used to make such selection. This header is forwardable.
=> Forward persona header

lib/manageiq/api/common/entitlement.rb, spec/lib/manageiq/api/common/entitlements_spec.rb
You can see current entitlements with:
```
curl https://cloud.redhat.com/api/entitlements/v1/services -u user:password
```
Example output:
```
{"hybrid_cloud":{"is_entitled":true},"insights":{"is_entitled":true},"openshift":{"is_entitled":true},"smart_management":{"is_entitled":true},"ansible":{"is_entitled":false},"migrations":{"is_entitled":true}}
```
=> Add new entitlements: Ansible and Migrations

lib/manageiq/api/common/paginated_response.rb, spec/lib/manageiq/api/common/paginated_response_spec.rb
=> Prevent first pages from having a "prev" page link

README.md, lib/manageiq/api/common/filter.rb, spec/dummy/app/controllers/api/v1/mixins/index_mixin.rb, spec/dummy/app/controllers/api/v1/sources_controller.rb, spec/dummy/app/controllers/api/v1x0.rb, spec/dummy/config/routes.rb, spec/requests/api/v1.0/filter_spec.rb
Adding support for case insensitive searches.
Approach taken here to support the case insensitive operators for the filter parameter in addition to the current string operators.
So adding support for:
- starts_with_i
- ends_with_i
- contains_i
- eq_i
This works with both REST API as well as GraphQL
=> Adding support for case insensitive searches.

lib/manageiq/api/common/open_api/docs/object_definition.rb, spec/dummy/public/doc/openapi-3-v1.0.0.json, spec/requests/params_spec.rb
The OpenApi::Docs::ObjectDefinition.all_attributes method was only
returning top level attribute names without considering that some of
those attributes might be nested objects.
This was causing the body_params.permit! to fail because it found nested
parameters.
https://github.com/ManageIQ/sources-api/issues/110
=> Fix nested attributes

lib/manageiq/api/common/filter.rb
After upgrading to manageiq-api-common v2.0.0 I got error details like:
"ManageIQ::API::Common::Filter::Error: ManageIQ::API::Common::Filter::Error"
With this change they're more like we would expect:
"ManageIQ::API::Common::Filter::Error: found unpermitted parameter: xxx"
=> Fix error responses for filtering

lib/manageiq/api/common/rbac/query_shared_resource.rb, lib/manageiq/api/common/rbac/share_resource.rb, spec/lib/manageiq/api/common/rbac/query_shared_resource_spec.rb, spec/lib/manageiq/api/common/rbac/share_resource_spec.rb, spec/lib/manageiq/api/common/rbac/unshare_resource_spec.rb
When the RBAC code was created in common gem it  was from the Approval source code
which uses the default scope to be principal (currently logged in user).
For Catalogs Sharing/Unsharing/Query feature we need to be in tenant
scope. This PR passes in the proper scope
=> Changed scope for sharing/unsharing to be account based

README.md, lib/manageiq/api/common/application_controller_mixins/parameters.rb, lib/manageiq/api/common/application_controller_mixins/request_parameter_validation.rb, lib/manageiq/api/common/graphql.rb, lib/manageiq/api/common/graphql/templates/query_type.erb, lib/manageiq/api/common/graphql/types/query_sort_by.rb, lib/manageiq/api/common/open_api/docs/doc_v3.rb, lib/manageiq/api/common/open_api/generator.rb, lib/manageiq/api/common/paginated_response.rb, spec/dummy/app/controllers/api/v1/mixins/index_mixin.rb, spec/dummy/app/controllers/api/v1/source_types_controller.rb, spec/dummy/app/controllers/api/v1x0.rb, spec/dummy/app/controllers/application_controller.rb, spec/dummy/config/routes.rb, spec/dummy/public/doc/openapi-3-v1.0.0.json, spec/requests/api/graphql_spec.rb, spec/requests/api/v1.0/filter_spec.rb
Added support for sort_by for sorting results.
- Supports a single string representing an attribute, attribute:asc or attribute:desc
- Supports array of attribute, attribute:asc and attribute:desc
Examples:
URL Query:
- GET /api/v1.0/sources?sort_by=name
- GET /api/v1.0/vms?sort_by[]=power_state&sort_by[]=memory:desc
Ruby Client Parameter:
- :sort_by => "name"
- :sort_by => ["power_state", "memory:desc"]
GraphQL Parameter:
- sort_by: "name"
- sort_by: ["power_state, "memory:desc"]
GraphQL Example:
```
{
sources(sort_by: ["source_type_id:asc", "uid:desc"]) {
source_type_id
id
name
uid
}
}
```
Or as simple as:
```
{
sources(sort_by: "name") {
id
name
}
}
```
Enhancement as per TPINVTRY-705
=> Added support for sort_by for sorting results.

lib/insights/api/common/application_controller_mixins/api_doc.rb, lib/insights/api/common/open_api/generator.rb, lib/insights/api/common/open_api/serializer.rb
For https://github.com/ManageIQ/topological_inventory-api/pull/259
- Loosen the ties between controller and model
- Look up the API doc definition based on the controller rather than the model
- Allow records to be serialized using a schema other than the model name
- Allow for API schemas that aren't backed by a model
=> Split model and controller

lib/insights/api/common/open_api/generator.rb
When generating the openapi file only write e.g. v1.0 not v1.0.0 so that
we can tag every API change without having to create new files
everytime.
=> Only write the x.y version when generating openapi

app/controllers/concerns/insights/api/common/tagging_methods.rb
Extracted from [topo-api](https://github.com/RedHatInsights/topological_inventory-api/blob/a99a329ae61f0b137cf1567b69970976946be0a0/app/controllers/api/v2x0/taggings_controller.rb#L15-L41) and [catalog-api](https://github.com/RedHatInsights/catalog-api/blob/96f11fd14d8ea652688d2b5fbbe71aecace67827/app/controllers/api/v1/tags_controller.rb#L22-L48) including https://github.com/RedHatInsights/catalog-api/pull/572
=> Add a concern for the #tag and #untag methods to share common code

lib/insights/api/common/status.rb, spec/requests/status_spec.rb
before, the Status API would just ping `ENV['DATABASE_URL']` and check
for ok, this does not work for connection strings that have flags on the
end such as catalog:
`postgresql://xxx:xxx@catalog-postgresql:5432/catalog_production?encoding=utf8&pool=5&wait_timeout=5`
This updates the code to handle such a connection string.
=> Update the Status Api for flags on `DATABASE_URL`

lib/insights/api/common/rbac/access.rb, spec/lib/insights/api/common/rbac/access_spec.rb
Change BYPASS_RBAC to only check for the value "true".
Based on changes in https://github.com/RedHatInsights/e2e-deploy/pull/1062 the `BYPASS_RBAC` setting was changed from not being set to defaulting to `false`.
The original logic was setup to bypass RBAC if the environment variable exists, regardless of the value.
=> Change BYPASS_RBAC to only check for the value "true"

lib/insights/api/common/open_api/docs/doc_v3.rb, lib/insights/api/common/open_api/generator.rb
This method name tripped me up for a bit as
I was thinking it was reading the base path off of disk.
I renamed it to help show that it pulls the value directly from the `servers` key
of the open api doc.
=> Rename base_path to server_base_path

app/models/concerns/insights/api/common/act_as_taggable_on.rb, lib/insights/api/common/engine.rb
This adds the act_as_taggable_on mixin from topology to Insights::API::Common to be shared by other projects.
Ref: https://github.com/RedHatInsights/sources-api/pull/177
=> Add the act_as_taggable_on mixin to API::Common

spec/support/user_header_spec_helper.rb
`IPP-14 Red Hat Insights User Identity` specifies that the auth_type is under the identity section not the internal section.
=> According to the IPP auth_type is in identity

lib/insights/api/common/request.rb, lib/insights/api/common/system.rb, lib/insights/api/common/tenant.rb, lib/insights/api/common/user.rb, spec/lib/insights/api/common/request_spec.rb, spec/lib/insights/api/common/system_spec.rb, spec/lib/insights/api/common/tenant_spec.rb, spec/support/user_header_spec_helper.rb
When a machine credential connects to 3scale there is no user key in the headers but rather a system key.
Depends on: https://github.com/RedHatInsights/insights-api-common-rails/pull/162
Relates to JIRA: https://projects.engineering.redhat.com/browse/TPINVTRY-870
=> Allow machine credentials access to the API

lib/insights/api/common/rbac/service.rb, spec/lib/insights/api/common/rbac/service_spec.rb
The Auto Generated clients use libcurl to perform network operations.
lib curl can detect
1. Connection failures (bad host, not reachable)
2. Timeout errors
3. Actual HTTP status codes coming from the API Server
https://github.com/RedHatInsights/insights-rbac-api-client-ruby/blob/41cddab91c06ef34abec537a8c83e08ca4a8d2be/lib/rbac-api-client/api_client.rb#L56
This PR adds the ability to make distinctions between Network Error, Time out error and actual API errors which allows the services to respond with appropriate HTTP error codes when communication between services fails (e.g. Catalog talking to RBAC service and the RBAC service is down)
=> Separate RBAC network error out from common errors

lib/insights/api/common/rbac/validate_groups.rb, spec/lib/insights/api/common/rbac/validate_groups_spec.rb
As discussed in Catalog PR https://github.com/RedHatInsights/catalog-api/pull/596, this change should probably live here since it will be used by both Catalog and Approval.
@mkanoor @syncrou @gmcculloug Please Review.
=> Move group validation to separate class and add specs

lib/insights/api/common/rbac/seed.rb, spec/data/test_seed.yml, spec/data/user.yml, spec/lib/insights/api/common/rbac/seed_spec.rb, spec/support/rbac_seed_context.rb
This PR contains just the seeding portion of this PR https://github.com/RedHatInsights/insights-api-common-rails/pull/137 which has been closed.
Instead of adding roles to group via Policies now we can directly add role to a group
=> Use add_role_to_group during seeding

lib/insights/api/common/rbac/service.rb, spec/lib/insights/api/common/rbac/service_spec.rb
Some RBAC calls require extra headers.
=> Accept user defined headers in RBAC calls

lib/insights/api/common/application_controller_mixins/parameters.rb, lib/insights/api/common/filter.rb, spec/dummy/app/controllers/api/v1/sources_controller.rb, spec/dummy/db/migrate/20200120165732_add_sources_undocumented_column.rb, spec/requests/api/v1.0/filter_spec.rb
- Switch to `arel_attribute(key)` to enable use of `virtual_delegates`
- Allow filtering on extra attributes
@kbrock Please review
=> Allow filtering of tag join records based on tag attributes

lib/insights/api/common/paginated_response_v2.rb, spec/dummy/app/controllers/api/v2/application_types_controller.rb, spec/dummy/app/controllers/api/v2/applications_controller.rb, spec/dummy/app/controllers/api/v2x0.rb, spec/dummy/app/models/application.rb, spec/dummy/app/models/application_type.rb, spec/dummy/config/routes.rb, spec/dummy/db/migrate/20200121140744_add_applications_and_application_types.rb, spec/dummy/public/doc/openapi-3-v2.0.0.json, spec/lib/insights/api/common/paginated_response_v2_spec.rb, spec/requests/api/v2.0/graphql_spec.rb, spec/requests/api/v2.0/paginated_response_spec.rb
- Adding support for sorting by association attribute and association count using the object based specification for the sort_by parameter.
_Note_: with sort_by coming in as hash parameters, GraphQL does not like periods or @ in parameter names, periods are gone, but the **@ count** needed to be changed, went with **__count**.
Fix for: TPINVTRY-770
Depends on: https://github.com/RedHatInsights/insights-api-common-rails/pull/165
=> Sort by association attribute and count

README.md
Updated the README.md to mention the new object type syntax for sort_by parameter as well as the filtering and sorting by association attribute as well as sorting by association count.
Dependencies:
=> Updated README.md for object syntax of sort_by and filtering and sorting by association

lib/insights/api/common/rbac/access.rb, spec/lib/insights/api/common/rbac/access_spec.rb
The RBAC team has changed the get_principal_access API to return all data in a single call and not use pagination. The data returned is still in the pagination format for backward compatibility
The old url used to look like
**http://rbac.rbac-ci.svc:8080/api/rbac/v1/access/?application=\u0026limit=500\u0026offset=0**
The new URL without the limit and offset looks like
**http://rbac.rbac-ci.svc:8080/api/rbac/v1/access/?application=**
This change doesn't effect the catalog and approval services
The PR from the RBAC service that brought in this change is
https://github.com/RedHatInsights/insights-rbac/pull/195
=> Remove the limits and offset to get data in single call

lib/insights/api/common/application_controller_mixins/exception_handling.rb, spec/dummy/app/controllers/api/v1x0.rb, spec/dummy/config/initializers/custom_exception_mappings.rb, spec/dummy/config/routes.rb, spec/requests/api/v1.0/filter_spec.rb, spec/requests/api/v2.0/paginated_response_spec.rb, spec/requests/exception_handling_spec.rb, spec/requests/request_body_validation_spec.rb, spec/requests/request_path_spec.rb
Fixes #178
Uses Rack::Utils.status_code to convert the Rails HTTP error symbols to
numeric values. The status_code can handle integers/strings/symbols and
returns the appropriate numeric value
e.g.
Rack::Utils.status_code(400) => 400
Rack::Utils.status_code("400") => 400
Rack::Utils.status_code(:forbidden) => 403
The JSON API Error Object Sample
https://jsonapi.org/examples/#error-objects-basics
The status value should be
https://jsonapi.org/format/#errors
status: the HTTP status code applicable to this problem, expressed as a string value.
=> Use rack to get proper status code

lib/insights/api/common/graphql/templates/query_type.erb, spec/lib/insights/api/common/graphql/generator_spec.rb
To get the arguments coming into GraphQL the args needs to be passed down to the base_query for any apps that have a custom resolver.
**This is a breaking change.** 
We discovered this during testing for Approval Service, we needed the id of the object that the user is requesting. The graphql gem passes in an args parameter as the second parameter. As shown here and several other places in the gem.
https://github.com/rmosolgo/graphql-ruby/blob/73ac09cb95a0b03b3f00c09921b65534f66d0ae6/spec/fixtures/upgrader/starrable.original.rb#L31
There are currently 2 known repos using this  gem for which this will  be a breaking change 
https://github.com/RedHatInsights/approval-api/blob/830f34c87db22b513b70a301f1907e4d80b29270/app/controllers/api/v1x0/graphql_controller.rb#L19 …
=> Added args to the base_query call

lib/insights/api/common/application_controller_mixins/exception_handling.rb, spec/dummy/app/controllers/api/v1x0.rb, spec/dummy/app/controllers/api_client_error.rb, spec/dummy/config/routes.rb, spec/requests/exception_handling_spec.rb
https://projects.engineering.redhat.com/browse/SSP-1437
Since Catalog interacts with multiple micro services, RBAC, Approval,
Topology etc, we need to percolate errors from the other services upto
the caller. Since the IPP recommends using JSON-API's error format which
is an array of error objects. This PR handles errors coming from
openapi-generated clients and converts them into error objects.
=> Percolate errors from different micro services

lib/insights/api/common/open_api/generator.rb
To conform with the IPP and the JSON API error object format
the generator should be using string for status.
https://jsonapi.org/format/#errors
This PR updates the pre-canned type used by the generator used by topology and sources when they generate the openapi.json so it can create the JSON API conformant type.
https://github.com/RedHatInsights/sources-api/blob/8782d2103bed61c40b547603089c0978624950e1/public/doc/openapi-3-v3.0.json#L1780
=> The status field in the error object is string

lib/insights/api/common/open_api/generator.rb
If there are duplicate operationIds we raise an exception with the generated method name and the offending class.
```
ArgumentError: operation id cannot be duplicates, listApplicationAuthentications in class ApplicationAuthentication has already been used in class Authentication
```
This PR allows a class to override the operation Id for list operations only for now by creating a class method called list_operation_id
e.g.
```
def self.list_operation_id
"listAllApplicationAuthentications"
end
```
This helps when we have 2 REST calls which use the same generated operationId a way to override ride as well as check for duplicates during the generations
GET /application_authentications         => listAllApplicationAuthentications
GET /applications/{id}/authentications => …
=> Enforce unique operation ids

lib/insights/api/common/request.rb, spec/lib/insights/api/common/request_spec.rb
https://github.com/ManageIQ/manageiq-loggers/blob/7e6d3c29b94bb4b73536c4431fb60ebba9aae9db/lib/manageiq/loggers/container.rb#L68
Added class methods to set the request_id to be compatible with
the manageiq logger
=> ManangeIQ Logger is deprecating the use of current_request

Gemfile, insights-api-common.gemspec, lib/insights/api/common/rbac/seed.rb, lib/insights/api/common/rbac/service.rb
Previously we were directly pointing to a git branch,
switching to use the new renamed gem from rubygems.org
Dependent on PR https://github.com/RedHatInsights/insights-rbac-api-client-ruby/pull/10
=> Switched to insights-rbac-api-client from rubygems

lib/insights/api/common/metrics.rb, spec/lib/insights/api/common/metrics_spec.rb
This is for https://github.com/RedHatInsights/topological_inventory-ingress_api/pull/87 and potentially other applications that are currently using the Common Metrics classes. 
Basically it allows passing in a hash defined by the application to register prometheus metrics and make helper methods for them as specified.
First pass only supports counters, but maybe I'll implement support for histograms etc in the future. 
example implementation: https://github.com/RedHatInsights/topological_inventory-ingress_api/pull/87
\# TODO:
=> Add support for custom prometheus metrics defined by the application

spec/lib/insights/api/common/user_spec.rb
Fixes #190
This is to remove the deprecation warning. The tenant/account number was moved into the request in this PR but the spec was never adjusted
This change was implemented in https://github.com/RedHatInsights/insights-api-common-rails/pull/162
=> Check for tenant directly in request

lib/insights/api/common/application_controller_mixins/exception_handling.rb, spec/requests/exception_handling_spec.rb
If the response body contains an invalid JSON we should not raise an exception. Usually happens if the server ran into some error and couldn't send back a valid response body. These are typically the 5xx errors, server side errors.
e.g this is live data that came back from the RBAC service
```
{"@timestamp":"2020-05-07T08:52:38.780751 ","hostname":"catalog-api-89-46qw4","pid":27,"tid":"2ad1404721ec","level":"err","message":"RBACApiClient::ApiError: Error message: the server returns an error\nHTTP status code: 500\nResponse headers: {\"Server\"=\u003e\"gunicorn/19.9.0\", \"Date\"      =\u003e\"Thu, 07 May 2020 08:52:38 GMT\", \"Connection\"=\u003e\"keep-alive\", \"Content-Type\"=\u003e\"text/html\", \"Content-Length\"=\u003e\"2      7\", \"Vary\"=\u003e\"Origin\"}\nResponse body: …
```
=> Handle scenarios where response body contains unparseable JSON

lib/insights/api/common.rb, lib/insights/api/common/application_controller_mixins/exception_handling.rb, lib/insights/api/common/custom_exceptions.rb, spec/dummy/app/controllers/api/v1x0.rb, spec/dummy/config/initializers/custom_exception_mappings.rb, spec/dummy/config/routes.rb, spec/lib/insights/api/common/custom_exceptions_spec.rb, spec/requests/exception_handling_spec.rb
In Catalog, we have an error that is being raised by a gem automatically, `Pundit::NotAuthorizedError`, which also auto-generates a not-so-user-friendly error message of `"not authorized to <action?> this Class"`.
We needed a way to hook into the `rescue_from` process without duplicating the code in common, so I broke out the handler into a separate method and I'm using it to pass control over the error message to the `rescue_from` we have for specifically handling `Pundit::NotAuthorizedError`s.
Example usage: [Catalog PR](https://github.com/RedHatInsights/catalog-api/pull/731).
Edit: I still broke out the handling code into a `rescue_from_handler` since it was a simple refactor and it allows us to potentially use it going forward, but we are not currently using it. Instead, common is …
=> Handle Pundit::NotAuthorizedError exceptions differently than general exceptions

lib/insights/api/common/metrics.rb, spec/lib/insights/api/common/metrics_spec.rb
Found out that we can't really disable these metrics, so we run into issues with multiple common-enabled apps that can't bind to the same port if running on localhost. 
This allows for disabling or setting a different port number if you really want the metrics.
=> Add the ability to disable metrics by setting METRICS_PORT=0

lib/insights/api/common/open_api/generator.rb
`nullable` attributes need to be kept when generating new json
**related**: https://github.com/RedHatInsights/sources-api/pull/231
=> Excluding existing 'nullable' attributes

.github/workflows/gem-push.yml
https://github.com/marketplace/actions/publish-to-rubygems
Uses that action, which just runs `rake release` at the project root, we just need two secrets:
- `GITHUB_TOKEN`
- `RUBYGEMS_API_KEY`
cc @gmcculloug @syncrou @slemrmartin
=> Add github workflow to release to rubygems automatically

.travis_scripts/openapi-validator.sh
Part of fixing #201
Move the `openapi-validator.sh` script to a common location for all the API repos to access.
=> Add openapi-validator.sh script for reference from API repos.

.travis_scripts/openapi-validator.sh
After spending some time with other travis scripts I started thinking it would be better to move the download of `openapi-generator-cli` to this common method instead of requiring each caller to have to download it separately as part of the `.travis.yaml`
It's not a big impact here (2 new lines), but the caller's `.travis.yml` file can be reduced to one line:
```diff
- - curl -L https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/bin/utils/openapi-generator-cli.sh
-   > ./openapi-generator-cli
- - chmod +x ./openapi-generator-cli
- - curl -L https://raw.githubusercontent.com/RedHatInsights/insights-api-common-rails/master/.travis_scripts/openapi-validator.sh
-   > ./openapi-validator.sh
- - chmod +x ./openapi-validator.sh
- - ./openapi-validator.sh
+ - curl -sSL …
```
=> Add download of openapi-generator script

lib/insights/api/common/custom_exceptions.rb, spec/lib/insights/api/common/custom_exceptions_spec.rb
This PR allows `authorize` to accept symbol as its second parameter, like `authorized(Portfolio, :update?)`, otherwise following `delete_suffix` will fail and raise other exceptions.
=> Make sure Pundit exception's query type is String

lib/insights/api/common/metrics.rb, spec/lib/insights/api/common/metrics_spec.rb
If `metrics_port` is zero then custom metric methods needs to be defined too. 
Cought in Ingress API with disabled metrics
=> Define custom metric methods even if port is zero

lib/insights/api/common/application_controller_mixins/exception_handling.rb, lib/insights/api/common/request.rb, spec/lib/insights/api/common/request_spec.rb
When exception is raised, the place to log error messages has lost the request context. This PR moves the log call within request context.
=> Fixed to log error messages in with_request block

.codeclimate.yml, insights-api-common.gemspec
Updating rubocop to 1.0.0 (also done for topological inventory + sources)
---
[RHCLOUD-10237](https://issues.redhat.com/browse/RHCLOUD-10237)
=> Rubocop update to 1.0.0

lib/insights/api/common/custom_exceptions.rb, spec/dummy/app/controllers/api/v1x0.rb, spec/lib/insights/api/common/custom_exceptions_spec.rb, spec/requests/exception_handling_spec.rb
When we check requirements for actions, we generally check against the parent Portfolio if the user has the permission to update the Portfolio. This happens for example when creating portfolio items or when editing surveys, resetting service plans, and various other actions for portfolio items and service plans.
However, because we're checking against a Portfolio, the way Pundit handles it if the check fails is that the record stored in the exception is now `Portfolio`, which ends up generating bad messages because the user will see "You are not authorized to _action_ for this Portfolio" when they were trying to create/edit either a portfolio item or a service plan. There's not a really great way that I could find to directly override the `exception.record` without monkeypatching Pundit …
=> Use custom error_message if a policy exposes it

lib/insights/api/common/application_controller_mixins/parameters.rb
So this was a fun one, after [updating Sources API](https://github.com/RedHatInsights/sources-api/pull/297) to use the common gem's `params_for_update` method I had some specs failing. 
After digging into it more, the test that was failing was here: https://github.com/lindgrenj6/sources-api/blob/b06b2db350482cd3f7738101bdbf51751362d1a2/spec/requests/api/v3.0/sources_spec.rb#L330-L340
The problem is that the `sanctified_permit_param` method was returning _every field in the api_doc_definition_ due to the face that `Enum#each` always returns the array, e.g. attributes in this case, which is a truthy value. It was allowing any field through. Here is the value of `strong_params_hash` on the "Source" record when updating:
```
[1] pry(#<Api::V3x0::SourcesController>)> pp strong_params_hash …
```
=> Make `Parameters#params_for_update` only include writeable fields in permit-hash

CHANGELOG.md, lib/insights/api/common/version.rb
Debating naming this release `4.2.0` instead of `4.1.6` due to the fact that `params_for_update` behavior is changing. Theoretically it should be a bug fix, but the behavior is changing nonetheless.
EDIT: After talking with Drew we decided to release 5.0 instead of a minor release due to the fact this is a breaking change that could introduce small intricacies in catalog and other apps using this code. 
cc @hsong-rh @eclarizio @syncrou
*DEPENDS ON*:
=> Release v5.0.0

CHANGELOG.md, insights-api-common.gemspec, lib/insights/api/common/version.rb
The `graphql` gem introduced a breaking change recently, I found it locally today in sources-api during development and @mkanoor found it on Catalog side as well.
Pinning to 1.11.7 for now while we wait to get it fixed.
=> Release 5.0.1

lib/insights/api/common/graphql/generator.rb, spec/lib/insights/api/common/graphql/generator_spec.rb
This allows to make GraphQL erb([model_type.erb](https://github.com/RedHatInsights/insights-api-common-rails/blob/master/lib/insights/api/common/graphql/templates/model_type.erb), [query_type.erb](https://github.com/RedHatInsights/insights-api-common-rails/blob/master/lib/insights/api/common/graphql/templates/query_type.erb), [schema.erb](https://github.com/RedHatInsights/insights-api-common-rails/blob/master/lib/insights/api/common/graphql/templates/schema.erb)) templates configurable in repo(For example in sources-api) where is insights-api-common-rails gem used and 
templates live in location  `./api/common/graphql/templates` in remote repos.
Example: So if you want override GraphQL schema for source-api, you 
need to create file in source-api repo like is this …
=> Allow to load GraphQL erb templates outside of repo

lib/insights/api/common/metrics.rb
When I tested clowder in minikube I got the problem that prometheus cannot bind to a port in localhost. The error message was `cannot assign requested address: localhost`. Changing to `127.0.0.1` solves the problem.
=> Bind to 127.0.0.1 instead of localhost

README.md, lib/insights/api/common/filter.rb, spec/requests/api/v1.0/filter_spec.rb
see https://issues.redhat.com/browse/RHCLOUD-10991
Adds comparators for checking that for checking not_equal. Follows the same pattern as in `nil` and `not_nil`.
**Strings**
- not_eq
- not_eq_i
**Integers**
- not_eq
=> Add not_eq comparators

lib/insights/api/common/application_controller_mixins/request_path.rb, spec/dummy/app/controllers/api/v2/tasks_controller.rb, spec/dummy/app/controllers/api/v2x0.rb, spec/dummy/app/models/source.rb, spec/dummy/app/models/task.rb, spec/dummy/config/routes.rb, spec/dummy/db/migrate/20190922115700_enable_pgcrypto_extension.rb, spec/dummy/db/migrate/20210429134638_create_tasks.rb, spec/dummy/public/doc/openapi-3-v2.0.0.json, spec/requests/request_path_spec.rb
This line caches the incorrect regex pattern
https://github.com/RedHatInsights/insights-api-common-rails/blob/b53ab53fab0c965886fba1bc46e3757b52dcdaf2/lib/insights/api/common/application_controller_mixins/request_path.rb#L47 
It should be looking at the passed in **primary_collection_name**
Current logic to validate ID will fail when sub collection objects have different ID patterns, it works only when all objects have the same regex pattern.
For example: if a task object's ID has uuid pattern, the API call `/sources/:id/tasks` may fail with error: `ID is invalid`. 
This PR replaces the cached regular expression with a hash, keyed of the primary_collection_name
If the user makes 2 API calls
"/api/v2.0/task/1234-5678-8899-90000...."
"/api/v2.0/sources/2334/tasks"
The first call will go …
=> Change to support object id with different patterns

lib/insights/api/common/error_document.rb, spec/dummy/app/controllers/api/v1x0.rb, spec/dummy/config/routes.rb, spec/requests/exception_handling_spec.rb
Sources API on CI produces: 
```
{"@timestamp":"2021-05-24T10:42:31.871175 ","hostname":"sources-api-1210-qlghn","pid":30,"tid":"2b04d7eb3334","level":"info","message":"Started GET \"/api/sources/v3.1/application_types/2/sources?filter%5Bid%5D=25613\" for 10.129.13.104 at 2021-05-24 10:42:31 +0000"}
--
{"@timestamp":"2021-05-24T10:42:31.872593 ","hostname":"sources-api-1210-qlghn","pid":30,"tid":"2b04d7eb3334","level":"info","message":"Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)"}
{"@timestamp":"2021-05-24T10:42:31.873434 ","hostname":"sources-api-1210-qlghn","pid":30,"tid":"2b04d7eb3334","level":"crit","message":"  "}
{"@timestamp":"2021-05-24T10:42:31.873520 ","hostname":"sources-api-1210-qlghn","pid":30,"tid":"2b04d7eb3334","level":"crit","message":"JSON::GeneratorE …
```
=> Ensure UTF-8 compatibility for ErrorDocument#to_h.to_json

lib/insights/api/common/filter.rb, lib/insights/api/common/graphql/generator.rb, lib/insights/api/common/graphql/templates/aggregate_model_type.erb, lib/insights/api/common/graphql/templates/aggregate_type.erb, lib/insights/api/common/graphql/templates/model_type.erb, lib/insights/api/common/graphql/templates/query_type.erb, spec/requests/api/v1.0/graphql_spec.rb
This PR adds to possibility to query aggregate metric `total_count`:
```
sources_aggregate(filter: { source_type: { vendor: { not_eq: "Red Hat"} } })
{
aggregate
{
total_count 
}
}
```
To query  `total_count` for `collection`: 
```
<collection>_aggregate
{
aggregate
{
total_count 
}
}
```
also with filtering as on collection:
```
<collection>_aggregate(filter: { source_type: { vendor: { not_eq: "Red Hat"} } })
{
aggregate
{
total_count 
}
}
```
Total count can be obtain without limits, offset but with filtering which was intended.
This aggregation can be also on nested associations(NOTE: There is no filtering on nested associations implemented, only limit, offset so filtering is not also present on nested aggregation):
```
query{
sources(limit:2, offset:0, sort_by:{created_at: "desc"}, …
```
=> Support total counts for GraphQL

insights-api-common.gemspec, lib/insights/api/common/logging.rb, spec/lib/insights/api/common/logging_spec.rb
This PR replaces `manageiq-loggers` gem with [insights-loggers-ruby](https://github.com/RedHatInsights/insights-loggers-ruby) gem.
Usage is proper in rails applications:
```ruby
app_name = "sources-api"
Insights::API::Common::Logging.activate(config, app_name)
```
1. 
This changes allows to support haberdasher and in order to use haberdasher, `LOG_HANDLER ` environment variable needs to be set:
```ruby
ENV['LOG_HANDLER'] = 'haberdasher'
```
`app_name` - optional parameter to set app_name - which is need for identification of source log message and it will be visible in `tags` and `labels`.
2.
Uses logger `Insights::Loggers::CloudWatch` instead of `ManageIQ::Loggers::CloudWatch`.
`Insights::Loggers::CloudWatch` we can control log levels:
- container logger by `ENV['CONTAINER_LOG_LEVEL']`
- …
=> Use insights logger gem
