spec/lib/manageiq/api/common/request_spec.rb
Refactor specs to avoid the with_request repetition.  Also include more
headers in the example requests.
@bdunne @syncrou Please review.
=> Add more specs and cover missing calls

README.md
Add some filter examples so we can refer to here from catalog/approval/topology/sources etc.
=> Add documentation for Filter parameter format

bin/promote
Extracted from catalog, sources, and approval.
@gtanzillo @gmcculloug Please review.
I realize this is a ui promotion script, but it's in manageiq-api-common.  Eventually we may want a *different* common location, but this should work for now.  Perhaps we should rename it to `ui-promote`?
=> Add promote script as extracted from the various services

README.md
Updated the Filtering section in the README to show the GraphQL syntax of the filter: parameter.
=> Include the GraphQL syntax for the filter: parameter

lib/manageiq/api/common/graphql/generator.rb, lib/manageiq/api/common/graphql/templates/model_type.erb
Adding support for service defined field resolvers via a schema overlay option
- providing serializer and virtual attribute functionality, the GraphQL way.
=> Adding support for service defined field resolvers via a schema overlay option

lib/manageiq/api/common/application_controller_mixins/api_doc.rb, lib/manageiq/api/common/application_controller_mixins/common.rb, lib/manageiq/api/common/application_controller_mixins/input_validation.rb, lib/manageiq/api/common/application_controller_mixins/request_body_validation.rb, spec/dummy/app/controllers/api/v1x0.rb, spec/dummy/app/controllers/application_controller.rb, spec/dummy/config/routes.rb, spec/dummy/public/doc/openapi-3-v1.0.0.json, spec/requests/request_body_validation_spec.rb
Extracted from sources-api ApplicationController
Related to TPINVTRY-186
=> Share request body validation

spec/dummy/public/doc/openapi-3-v1.0.0.json, spec/requests/request_body_validation_spec.rb
Added a test case for checking when required properties in the openapi.json is not specified in the post request.
=> Added test for missing required parameter

lib/manageiq/api/common/application_controller_mixins/request_body_validation.rb, spec/requests/request_body_validation_spec.rb
Some of the post might not have a body, return an empty hash
if the body is empty
=> Allow for empty bodies

lib/manageiq/api/common/application_controller_mixins/api_doc.rb, lib/manageiq/api/common/application_controller_mixins/request_path.rb, spec/dummy/app/controllers/api/v1x0.rb, spec/dummy/config/routes.rb, spec/dummy/public/doc/openapi-3-v1.0.0.json, spec/lib/manageiq/api/common/application_controller_mixins/request_path_spec.rb, spec/requests/request_path_spec.rb
If invalid, return a 400 error response
Fixes TPINVTRY-675
Fixes TPINVTRY-676
=> Validate IDs when provided in the request path

lib/manageiq/api/common/application_controller_mixins/parameters.rb, spec/dummy/app/controllers/api/v1x0.rb, spec/dummy/app/controllers/application_controller.rb, spec/dummy/app/models/person.rb, spec/dummy/config/routes.rb, spec/dummy/public/doc/openapi-3-v1.0.0.json, spec/requests/params_spec.rb
Moved code from sources-api into the common gem for strong parameter check based on openapi.json
The original code was here
https://github.com/ManageIQ/sources-api/blob/0c096f39ee826b8269e79a28bc01475183ae2475/app/controllers/application_controller.rb#L74
=> Parameter mixin

manageiq-api-common.gemspec
There is a new version of openapi released which has my fix for array validation.
https://github.com/ota42y/openapi_parser/issues/47
=> Use new openapi parser

lib/manageiq/api/common/graphql.rb, lib/manageiq/api/common/graphql/generator.rb, lib/manageiq/api/common/graphql/templates/query_type.erb, spec/lib/manageiq/api/common/graphql/generator_spec.rb
Adding GraphQL::Generator test for the schema_overlay logic to test base_query
Fixes #92
=> Adding GraphQL::Generator tests

spec/support/user_header_spec_helper.rb
Followup to https://github.com/ManageIQ/manageiq-api-common/pull/113 and required for testing in catalog and approval repos.
Required by https://github.com/ManageIQ/catalog-api/pull/413
=> Add ansible and migrations to UserHeaderSpecHelper

lib/manageiq/api/common/paginated_response.rb, spec/lib/manageiq/api/common/paginated_response_spec.rb
=> Fix next and prev links

lib/manageiq/api/common/graphql.rb
Was missing the GraphQL Request reference for the OpenAPI Generator
=> Missing the GraphQL Request reference for the OpenAPI Generator

lib/manageiq/api/common/open_api/generator.rb
Related to https://github.com/ManageIQ/sources-api/pull/95
https://projects.engineering.redhat.com/browse/TPINVTRY-232
=> Add 404 "not found" to generated responses

lib/manageiq/api/common/rbac/seed.rb
This PR https://github.com/ManageIQ/catalog-api/pull/391 was
created after we had the PR to move the RBAC into the common
gem
=> We missed the changes needed for seeding

spec/dummy/public/doc/openapi-3-v1.0.0.json, spec/requests/api/v1.0/filter_spec.rb
=> Add specs for filtering

lib/insights/api/common/application_controller_mixins/request_body_validation.rb, lib/insights/api/common/open_api/generator.rb
Change tag definitions to request and return an array response
=> Allow for array body

lib/insights/api/common/open_api/generator.rb
- Updated the OpenAPI generator to reflect the new object  definition for the sort_by attribute.
=> Updated the OpenAPI generator for the object schema of sort_by

lib/insights/api/common/rbac/validate_groups.rb, spec/lib/insights/api/common/rbac/validate_groups_spec.rb
This was added by the RBAC team in
https://github.com/RedHatInsights/insights-rbac/pull/243
=> Implement group_uuid filtering

insights-api-common.gemspec
Use the latest openapi-parser it has additional uuid format check.
=> Use new openapi-parser

insights-api-common.gemspec
CodeClimate currently does not support SimpleCov 0.18
=> Lock SimpleCov to version 0.17

insights-api-common.gemspec
Bumped Rails and Rake versions to address issues identified by Hakiri
=> Keeping up with the Hakiris

CHANGELOG.md, insights-api-common.gemspec, lib/insights/api/common/version.rb
=> Pin cloudwatchloggers gem to ~>0.2.1

CHANGELOG.md, lib/insights/api/common/version.rb
=> Release v4.1.5

.rubocop.yml, .rubocop_base.yml
https://issues.redhat.com/browse/RHCLOUD-10237
Rather than making a new repo lets use api-common as the main repo. We will need to update ALL THE THINGS after this is merged though!
=> Add rubocop_base.yml for common rubocop rules

CHANGELOG.md, lib/insights/api/common/version.rb
Releasing changes from #220 and #221
=> Release v5.0.2

CHANGELOG.md, lib/insights/api/common/version.rb
Releasing the graphQL aggregate count changes.
=> Release v5.0.5
